### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2018/PInfo3#1]
Dear SoftAware,

This is your repository.
Please store all your developed code here, so we can verify your progress throughout the semester.
Feel free to use issues such as this one to communicate amongst each other, with me and with @mencattini .

Your VM Server will be pinfo2 (IP: 129.194.69.134 ).
Your logins are not activated yet, I hope it will be done by the end of this week.

Next to the official assignment (work out a project proposal),
I ask you to do the following initial tasks:

* Each team member should comment on this post, to verify that you receive these notifications.
* Create a README file for this repo (add some text, list the team members, etc.)

Best of luck

**Comment by amir74** [comment]
read and noted

**Comment by terryvogelsang** [comment]
OK

**Comment by matteo113** [comment]
OK

**Comment by Ornymama** [comment]
ok

**Comment by zuerchk3** [comment]
gi for a comment to receive nice notifications...

**Comment by Ornymama** [comment]
YES
