### ISSUE TITLE
VM ready

### ISSUE THREAD

**Issue by stklik** [unige-pinfo-2018/PInfo3#2]
Nicolas Mayencourt just informed me that your VMs are ready.

Please look at #1 where your server IP is provided.
Try SSH to connect to the machine with your university user + password.

The person specified as SysAdmin should have also been added to the sudoers file.
The SysAdmin should also verify their admin powers.

Contact me if anyone has problems logging in.

**Comment by terryvogelsang** [comment]
Everything seems ok thank you
